version: '3'
services:
# Nginxコンテナ
  nginx:
    container_name: nginx_fastapi_spro
    image: nginx:alpine
    depends_on:
      - app
      - db
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker_conf/nginx/conf.d:/etc/nginx/conf.d
      - ./docker_conf/nginx/ssl:/etc/nginx/ssl
    networks:
      fastapi_spro:
        ipv4_address: 172.27.1.11

# アプリケーションコンテナ
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_fastapi_spro
    volumes:
      - .:/fastapi/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOSTPWD=${PWD}
      - PYTHONPATH=/fastapi
    expose:
      - 8000
    depends_on:
      - db
    # args: host port user password database 
    entrypoint: /fastapi/docker_conf/wait_postgres.sh db 5432 root password spro
    command: bash /fastapi/docker_conf/runner.sh
    restart: always
    tty: true
    networks:
      fastapi_spro:
        ipv4_address: 172.27.1.12


# DBコンテナ
  db:
    image: postgres:12.4-alpine
    container_name: db_fastapi_spro
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spro
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
      - PGDATA=/var/lib/postgresql/data/fastapi
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      fastapi_spro:
        ipv4_address: 172.27.1.13

volumes:
  db_data:
    driver: local

networks:
  fastapi_spro:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/24
